name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - test/kgrabowski
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build

      - run: ls -lh build/googletest-release-1.7.0/CMakeFiles/gtest.dir/src/gtest-all.cc.o
      - run: ls -lh googletest-release-1.7.0/src/gtest-all.cc
