name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ci/openadr-ven-library:latest
      -
        name: Run unit tests
        run: |
          echo 'TEST_RESULT<<EOF' >> $GITHUB_ENV
          docker run ci/openadr-ven-library:latest /bin/sh -c "cd /open-adr-ven-library/build/debug && ./testoadr" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      -
        name: Check unit test result
          echo $TEST_RESULT | grep "[  PASSED  ]"
          echo $TEST_RESULT | grep "[  FAILED  ]"