name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/ci/openadr-ven-library:latest
      -
        name: Run unit tests
        run: docker run localhost:5000/ci/openadr-ven-library:latest /bin/sh -c "cd /open-adr-ven-library/build/debug && ./testoadr"
